### ISSUE TITLE
Bigger db than ram, gevent, mmap, yield on page fault

### ISSUE THREAD

**Issue by ddorian** [coleifer/greendb#1]
Hi,

Nice db you have there. When accessing a key from a database bigger than ram, lmdb will try reading with mmap, it won't be in-memory and it will do a `page fault`. Does gevent in this case `yield` so other greenlets continue or does it block the whole process ?

regards

**Comment by coleifer** [comment]
The map size is a strict upper-bound on the database size. So you need to size your map ahead-of-time to ensure you can hold everything. Exceeding the size of the map (via a write of some kind) will result in a `CommandError` error:

```python
CommandError: Unhandled server error: "mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached"
```

You can see some notes here: https://lmdb.readthedocs.io/en/release/

**Comment by ddorian** [comment]
Whem map-size > memory and db-size bigger > memory.
Accessing a key, in a page that isn't in-memory, will result in a page fault, and the kernel pauses the thread/processes so others can continue.

In this case, does it pause the whole process/thread or just the greenlet ?

**Comment by coleifer** [comment]
Gevent's event loop only covers what it can monkeypatch, stuff like socket io, so no.
